# Generated by cucumber-sinatra. (2014-09-22 14:07:09 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/lameune.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = LaMeune

class LaMeuneWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  LaMeuneWorld.new
end
